/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackToHome: typeof import('./src/components/BackToHome.vue')['default']
    DarkModeToggle: typeof import('./src/components/DarkModeToggle.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    DefineInput: typeof import('./src/components/DefineInput.vue')['default']
    Dependents: typeof import('./src/components/Dependents.vue')['default']
    Examples: typeof import('./src/components/Examples.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    RouterEntry: typeof import('./src/components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ToggleDarkMode: typeof import('./src/components/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./src/components/ToggleLanguage.vue')['default']
    Vue3_3Demo: typeof import('./src/components/Vue3_3Demo.vue')['default']
    VueUseMotion: typeof import('./src/components/VueUseMotion.vue')['default']
  }
}
