/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    BaseAppBar: typeof import('./src/components/BaseAppBar.vue')['default']
    Blank: typeof import('./src/layouts/blank.vue')['default']
    Code: typeof import('./src/components/Code.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    DefineInput: typeof import('./src/components/DefineInput.vue')['default']
    FullScreenTapEffects: typeof import('./src/components/FullScreenTapEffects.vue')['default']
    GitHub: typeof import('./src/components/GitHub.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MagicalEffects: typeof import('./src/components/MagicalEffects.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    RouterEntry: typeof import('./src/components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    ToggleDarkMode: typeof import('./src/components/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./src/components/ToggleLanguage.vue')['default']
    Vue3_3Demo: typeof import('./src/components/Vue3_3Demo.vue')['default']
    VueUseMotion: typeof import('./src/components/VueUseMotion.vue')['default']
  }
}
