/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/layouts/BaseLayout.vue')['default']
    BaseLayoutAside: typeof import('./src/layouts/BaseLayoutAside.vue')['default']
    Blank: typeof import('./src/layouts/blank.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    GitHub: typeof import('./src/components/GitHub.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    RouterEntry: typeof import('./src/components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
