/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"icon-nuxt" | "icon-pixel-travel-icon-停车" | "icon-pixel-travel-icon-冰淇淋" | "icon-pixel-travel-icon-冲浪" | "icon-pixel-travel-icon-指南针" | "icon-pixel-travel-icon-日历" | "icon-pixel-travel-icon-星宿" | "icon-pixel-travel-icon-晴天" | "icon-pixel-travel-icon-比基尼" | "icon-pixel-travel-icon-民宿" | "icon-pixel-travel-icon-沙滩" | "icon-pixel-travel-icon-泳裤" | "icon-pixel-travel-icon-游泳圈" | "icon-pixel-travel-icon-照片" | "icon-pixel-travel-icon-相机" | "icon-pixel-travel-icon-自行车" | "icon-pixel-travel-icon-自驾游" | "icon-pixel-travel-icon-行李箱" | "icon-pixel-travel-icon-购物" | "icon-pixel-travel-icon-阴天" | "icon-pixel-travel-icon-飞机">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"icon-nuxt" | "icon-pixel-travel-icon-停车" | "icon-pixel-travel-icon-冰淇淋" | "icon-pixel-travel-icon-冲浪" | "icon-pixel-travel-icon-指南针" | "icon-pixel-travel-icon-日历" | "icon-pixel-travel-icon-星宿" | "icon-pixel-travel-icon-晴天" | "icon-pixel-travel-icon-比基尼" | "icon-pixel-travel-icon-民宿" | "icon-pixel-travel-icon-沙滩" | "icon-pixel-travel-icon-泳裤" | "icon-pixel-travel-icon-游泳圈" | "icon-pixel-travel-icon-照片" | "icon-pixel-travel-icon-相机" | "icon-pixel-travel-icon-自行车" | "icon-pixel-travel-icon-自驾游" | "icon-pixel-travel-icon-行李箱" | "icon-pixel-travel-icon-购物" | "icon-pixel-travel-icon-阴天" | "icon-pixel-travel-icon-飞机">;
          default: string;
          required: true;
      };
  }>>, {
      name: "icon-nuxt" | "icon-pixel-travel-icon-停车" | "icon-pixel-travel-icon-冰淇淋" | "icon-pixel-travel-icon-冲浪" | "icon-pixel-travel-icon-指南针" | "icon-pixel-travel-icon-日历" | "icon-pixel-travel-icon-星宿" | "icon-pixel-travel-icon-晴天" | "icon-pixel-travel-icon-比基尼" | "icon-pixel-travel-icon-民宿" | "icon-pixel-travel-icon-沙滩" | "icon-pixel-travel-icon-泳裤" | "icon-pixel-travel-icon-游泳圈" | "icon-pixel-travel-icon-照片" | "icon-pixel-travel-icon-相机" | "icon-pixel-travel-icon-自行车" | "icon-pixel-travel-icon-自驾游" | "icon-pixel-travel-icon-行李箱" | "icon-pixel-travel-icon-购物" | "icon-pixel-travel-icon-阴天" | "icon-pixel-travel-icon-飞机";
  }>;
  export const svgNames: ["icon-nuxt", "icon-pixel-travel-icon-停车", "icon-pixel-travel-icon-冰淇淋", "icon-pixel-travel-icon-冲浪", "icon-pixel-travel-icon-指南针", "icon-pixel-travel-icon-日历", "icon-pixel-travel-icon-星宿", "icon-pixel-travel-icon-晴天", "icon-pixel-travel-icon-比基尼", "icon-pixel-travel-icon-民宿", "icon-pixel-travel-icon-沙滩", "icon-pixel-travel-icon-泳裤", "icon-pixel-travel-icon-游泳圈", "icon-pixel-travel-icon-照片", "icon-pixel-travel-icon-相机", "icon-pixel-travel-icon-自行车", "icon-pixel-travel-icon-自驾游", "icon-pixel-travel-icon-行李箱", "icon-pixel-travel-icon-购物", "icon-pixel-travel-icon-阴天", "icon-pixel-travel-icon-飞机"];
  export type SvgName = "icon-nuxt" | "icon-pixel-travel-icon-停车" | "icon-pixel-travel-icon-冰淇淋" | "icon-pixel-travel-icon-冲浪" | "icon-pixel-travel-icon-指南针" | "icon-pixel-travel-icon-日历" | "icon-pixel-travel-icon-星宿" | "icon-pixel-travel-icon-晴天" | "icon-pixel-travel-icon-比基尼" | "icon-pixel-travel-icon-民宿" | "icon-pixel-travel-icon-沙滩" | "icon-pixel-travel-icon-泳裤" | "icon-pixel-travel-icon-游泳圈" | "icon-pixel-travel-icon-照片" | "icon-pixel-travel-icon-相机" | "icon-pixel-travel-icon-自行车" | "icon-pixel-travel-icon-自驾游" | "icon-pixel-travel-icon-行李箱" | "icon-pixel-travel-icon-购物" | "icon-pixel-travel-icon-阴天" | "icon-pixel-travel-icon-飞机";
  export default SvgIcon;
}
