/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/example/': RouteRecordInfo<'/example/', '/example', Record<never, never>, Record<never, never>>,
    '/example/echarts': RouteRecordInfo<'/example/echarts', '/example/echarts', Record<never, never>, Record<never, never>>,
    '/example/naive-ui': RouteRecordInfo<'/example/naive-ui', '/example/naive-ui', Record<never, never>, Record<never, never>>,
    '/example/threejs': RouteRecordInfo<'/example/threejs', '/example/threejs', Record<never, never>, Record<never, never>>,
    '/example/use-number-animation': RouteRecordInfo<'/example/use-number-animation', '/example/use-number-animation', Record<never, never>, Record<never, never>>,
  }
}
